#!/bin/bash

ophub_release_file="/etc/ophub-release"

preset_log="/tmp/armbian-preset.log"

# Add log
tolog() {
    echo -e "${1}"
    echo -e "[$(date +"%Y.%m.%d.%H:%M:%S")] ${1}" >>${fix_log}
}

# Show start message
echo "" >${fix_log} && tolog "Start presetting..."

[[ -f "${ophub_release_file}" ]] && {
    # Get welcome banner value
    family_name="$(cat ${ophub_release_file} | grep -E "^FAMILY=" | cut -d"'" -f2)"
    platform_name="$(cat ${ophub_release_file} | grep -E "^PLATFORM=" | cut -d"'" -f2)"
    soc_name="$(cat ${ophub_release_file} | grep -E "^SOC=" | cut -d"'" -f2 | sed -e "s|\b[a-z]|\U&|g")"
    board_name="$(cat ${ophub_release_file} | grep -E "^BOARD=" | cut -d"'" -f2 | sed -e "s|\b[a-z]|\U&|g")"

    tolog "00. Welcome banner: ${family_name} ${platform_name} ${soc_name} ${board_name}"
}
