#!/bin/bash

ophub_release_file="/etc/ophub-release"
fp_config="/root/.not_logged_in_yet"

preset_log="/tmp/armbian-preset.log"

# Add log
tolog() {
    echo -e "${1}"
    echo -e "[$(date +"%Y.%m.%d.%H:%M:%S")] ${1}" >>${preset_log}
}

# Show start message
echo "" >${preset_log} && tolog "Start presetting..."

[[ -f "${ophub_release_file}" ]] && {
    # Get welcome banner value
    family_name="$(cat ${ophub_release_file} | grep -E "^FAMILY=" | cut -d"'" -f2)"
    platform_name="$(cat ${ophub_release_file} | grep -E "^PLATFORM=" | cut -d"'" -f2)"
    soc_name="$(cat ${ophub_release_file} | grep -E "^SOC=" | cut -d"'" -f2 | sed -e "s|\b[a-z]|\U&|g")"
    board_name="$(cat ${ophub_release_file} | grep -E "^BOARD=" | cut -d"'" -f2 | sed -e "s|\b[a-z]|\U&|g")"

    tolog "00. Welcome banner: ${family_name} ${platform_name} ${soc_name} ${board_name}"

    [[ -f ${fp_config} ]] && {
        random_passwd = $(openssl rand -base64 12)
        sed -i "s|^PRESET_ROOT_PASSWORD=.*|PRESET_ROOT_PASSWORD='${random_passwd}'|g" ${fp_config}
        sed -i "s|^PRESET_USER_PASSWORD=.*|PRESET_USER_PASSWORD='${random_passwd}'|g" ${fp_config}
        tolog "01. Set random root password: ${random_passwd}"
    }
}
